const CACHE_NAME = 'v117';
const ASSETS_TO_CACHE = [
    './index.html',
    './platform.css',
    './hdd.webp',
    './manifest.json',
    './sw.js',
    './README.md',
    './assets/icons/icon.svg',
    './docs/NAVIGATION.md',
    './docs/constitution.md',
    './docs/the_book.md',
    './lark/0-firmware/BootLoader.js',
    './lark/0-firmware/HardwareRegistry.js',
    './lark/0-firmware/adapters/AudioAdapter.js',
    './lark/0-firmware/adapters/DisplayAdapter.js',
    './lark/0-firmware/adapters/KeyboardAdapter.js',
    './lark/0-firmware/adapters/NetworkAdapter.js',
    './lark/0-firmware/adapters/PointerAdapter.js',
    './lark/0-firmware/adapters/StorageAdapter.js',
    './lark/1-kernel/AppRegistry.js',
    './lark/1-kernel/DriverManager.js',
    './lark/1-kernel/DriverRegistry.js',
    './lark/1-kernel/KernelBootstrapContext.js',
    './lark/1-kernel/KernelResourceManager.js',
    './lark/1-kernel/PanicHandler.js',
    './lark/1-kernel/ServiceRegistry.js',
    './lark/1-kernel/ServiceWorkerManager.js',
    './lark/1-kernel/SystemEventBus.js',
    './lark/1-kernel/api/KernelAudioAPI.js',
    './lark/1-kernel/api/KernelDisplayAPI.js',
    './lark/1-kernel/api/KernelInputAPI.js',
    './lark/1-kernel/api/KernelNetworkAPI.js',
    './lark/1-kernel/api/KernelStorageAPI.js',
    './lark/1-kernel/boot/ApplicationBootstrap.js',
    './lark/1-kernel/boot/BootLogger.js',
    './lark/1-kernel/boot/DriverBootstrap.js',
    './lark/1-kernel/boot/ManagerBootstrap.js',
    './lark/1-kernel/boot/ServiceBootstrap.js',
    './lark/1-kernel/boot/StorageBootstrap.js',
    './lark/1-kernel/boot/services/ApplicationServices.js',
    './lark/1-kernel/boot/services/CapabilityServices.js',
    './lark/1-kernel/boot/services/CoreServices.js',
    './lark/1-kernel/boot/services/DesktopServices.js',
    './lark/1-kernel/boot/services/FilesystemServices.js',
    './lark/1-kernel/boot/services/UserServices.js',
    './lark/1-kernel/drivers/AudioDriver.js',
    './lark/1-kernel/drivers/BaseDriver.js',
    './lark/1-kernel/drivers/DisplayDriver.js',
    './lark/1-kernel/drivers/DisplayGraphicsDriver.js',
    './lark/1-kernel/drivers/KeyboardDriver.js',
    './lark/1-kernel/drivers/NetworkDriver.js',
    './lark/1-kernel/drivers/PointerDriver.js',
    './lark/1-kernel/drivers/StorageDriver.js',
    './lark/1-kernel/handles/AudioHandle.js',
    './lark/1-kernel/handles/DisplayHandle.js',
    './lark/1-kernel/handles/InputHandle.js',
    './lark/1-kernel/handles/NetworkHandle.js',
    './lark/1-kernel/handles/StorageHandle.js',
    './lark/1-kernel/kernel.js',
    './lark/1-kernel/utils/ObjectUtils.js',
    './lark/2-storage/IndexedDBStorageDriver.js',
    './lark/2-storage/LRFS.js',
    './lark/2-storage/LocalStorageDriver.js',
    './lark/3-system/BootMode.js',
    './lark/3-system/Environment.js',
    './lark/3-system/EnvironmentType.js',
    './lark/3-system/LogCategory.js',
    './lark/3-system/LogSeverity.js',
    './lark/3-system/SystemVersion.js',
    './lark/3-system/WindowStates.js',
    './lark/3-system/errors/LarkErrors.js',
    './lark/4-policies/InputPolicy.js',
    './lark/4-policies/ProcessPolicy.js',
    './lark/4-policies/RecoveryPolicy.js',
    './lark/4-policies/RestorePolicy.js',
    './lark/4-policies/SecurityPolicy.js',
    './lark/5-platform/boot/BootOrchestrator.js',
    './lark/5-platform/boot/BootSplash.js',
    './lark/5-platform/boot/ShutdownOrchestrator.js',
    './lark/5-platform/browser/BrowserStorageService.js',
    './lark/5-platform/capabilities/CapabilityRegistry.js',
    './lark/5-platform/capabilities/CapabilityService.js',
    './lark/5-platform/capabilities/providers/CapabilityProvider.js',
    './lark/5-platform/capabilities/providers/ClipboardCapabilityProvider.js',
    './lark/5-platform/capabilities/providers/DialogCapabilityProvider.js',
    './lark/5-platform/capabilities/providers/NetworkCapabilityProvider.js',
    './lark/5-platform/capabilities/providers/NotificationCapabilityProvider.js',
    './lark/5-platform/capabilities/providers/ProcessCapabilityProvider.js',
    './lark/5-platform/clipboard/ClipboardManager.js',
    './lark/5-platform/clipboard/ClipboardService.js',
    './lark/5-platform/commands/DiskCommands.js',
    './lark/5-platform/commands/FileCommands.js',
    './lark/5-platform/commands/HelpCommands.js',
    './lark/5-platform/commands/IPCCommands.js',
    './lark/5-platform/commands/NotificationCommands.js',
    './lark/5-platform/commands/PowerCommands.js',
    './lark/5-platform/commands/ProcessCommands.js',
    './lark/5-platform/commands/SystemCommands.js',
    './lark/5-platform/commands/UserCommands.js',
    './lark/5-platform/common/Result.js',
    './lark/5-platform/contextmenu/ContextMenuManager.js',
    './lark/5-platform/contextmenu/ContextMenuService.js',
    './lark/5-platform/desktop/DesktopEnvironmentService.js',
    './lark/5-platform/desktop/DesktopPolicy.js',
    './lark/5-platform/desktop/StartupApplicationOrchestrator.js',
    './lark/5-platform/desktop/WallpaperService.js',
    './lark/5-platform/desktop/shell/ContextMenuSurface.js',
    './lark/5-platform/desktop/shell/DialogSurface.js',
    './lark/5-platform/desktop/shell/NotificationSurface.js',
    './lark/5-platform/desktop/shell/OnScreenKeyboardSurface.js',
    './lark/5-platform/desktop/shell/PresentationEffectsBridge.js',
    './lark/5-platform/desktop/shell/SearchSurface.js',
    './lark/5-platform/desktop/shell/ShellComponent.js',
    './lark/5-platform/desktop/shell/ShutdownScreen.js',
    './lark/5-platform/desktop/shell/TaskbarSurface.js',
    './lark/5-platform/desktop/shell/WallpaperSurface.js',
    './lark/5-platform/desktop/shell/WatermarkSurface.js',
    './lark/5-platform/desktop/shell/WidgetSurface.js',
    './lark/5-platform/desktop/shell/WindowSurface.js',
    './lark/5-platform/desktop/shell/WindowSwitcherSurface.js',
    './lark/5-platform/dialog/DialogManager.js',
    './lark/5-platform/dialog/DialogService.js',
    './lark/5-platform/dialog/FilePickerDialog.js',
    './lark/5-platform/environments/EnvironmentManager.js',
    './lark/5-platform/environments/desktop/Desktop.js',
    './lark/5-platform/environments/desktop/MinimalDesktopEnvironment.js',
    './lark/5-platform/environments/platform/Lock.js',
    './lark/5-platform/environments/platform/Login.js',
    './lark/5-platform/environments/platform/OOBE.js',
    './lark/5-platform/environments/platform/OobeEnvironment.js',
    './lark/5-platform/environments/platform/PlatformEnvironmentRegistry.js',
    './lark/5-platform/environments/platform/PlatformEnvironmentSurface.js',
    './lark/5-platform/environments/platform/Recovery.js',
    './lark/5-platform/environments/platform/SetupEnvironment.js',
    './lark/5-platform/environments/platform/Shutdown.js',
    './lark/5-platform/environments/platform/steps/createDiskWizardStep.js',
    './lark/5-platform/environments/platform/steps/diskCheckStep.js',
    './lark/5-platform/environments/platform/steps/installedConfirmationStep.js',
    './lark/5-platform/environments/platform/steps/oobeConfirmPasswordStep.js',
    './lark/5-platform/environments/platform/steps/oobeGraphicsStep.js',
    './lark/5-platform/environments/platform/steps/oobeHintStep.js',
    './lark/5-platform/environments/platform/steps/oobeNameStep.js',
    './lark/5-platform/environments/platform/steps/oobePasswordStep.js',
    './lark/5-platform/environments/platform/steps/setupCompleteStep.js',
    './lark/5-platform/environments/platform/steps/virtualDiskCreatedStep.js',
    './lark/5-platform/environments/platform/steps/welcomeStep.js',
    './lark/5-platform/extensions/ExtensionRepositoryManager.js',
    './lark/5-platform/extensions/ExtensionService.js',
    './lark/5-platform/filesystem/DiskManager.js',
    './lark/5-platform/filesystem/DiskService.js',
    './lark/5-platform/filesystem/FileService.js',
    './lark/5-platform/filesystem/ImageStorageAdapter.js',
    './lark/5-platform/filesystem/validation/ManifestValidator.js',
    './lark/5-platform/filesystem/validation/rules/ExtensionRule.js',
    './lark/5-platform/filesystem/validation/rules/PermissionRule.js',
    './lark/5-platform/filesystem/validation/rules/RequiredFieldRule.js',
    './lark/5-platform/filesystem/validation/rules/RuntimeRule.js',
    './lark/5-platform/filesystem/validation/rules/SdkVersionRule.js',
    './lark/5-platform/graphics/PresentationEffectsService.js',
    './lark/5-platform/guardian/GuardianHistoryManager.js',
    './lark/5-platform/guardian/GuardianOrchestrator.js',
    './lark/5-platform/guardian/GuardianService.js',
    './lark/5-platform/guardian/GuardianValidationRegistry.js',
    './lark/5-platform/guardian/modules/ArchitectureValidationModule.js',
    './lark/5-platform/guardian/modules/ConfigurationValidationModule.js',
    './lark/5-platform/guardian/modules/DiskIntegrityValidationModule.js',
    './lark/5-platform/guardian/modules/PerformanceValidationModule.js',
    './lark/5-platform/guardian/modules/StorageHealthValidationModule.js',
    './lark/5-platform/info/SystemInformationService.js',
    './lark/5-platform/input/KeyboardLayouts.js',
    './lark/5-platform/ipc/CommandService.js',
    './lark/5-platform/ipc/IPCManager.js',
    './lark/5-platform/ipc/IPCService.js',
    './lark/5-platform/logging/ErrorService.js',
    './lark/5-platform/logging/LogManager.js',
    './lark/5-platform/logging/LogService.js',
    './lark/5-platform/network/DownloadService.js',
    './lark/5-platform/network/NetworkManager.js',
    './lark/5-platform/network/NetworkService.js',
    './lark/5-platform/notifications/NotificationManager.js',
    './lark/5-platform/notifications/NotificationService.js',
    './lark/5-platform/packages/ApplicationDatabaseManager.js',
    './lark/5-platform/packages/ApplicationDatabaseService.js',
    './lark/5-platform/packages/ApplicationIntentService.js',
    './lark/5-platform/packages/ApplicationService.js',
    './lark/5-platform/packages/AssociationService.js',
    './lark/5-platform/packages/PackageInstallOrchestrator.js',
    './lark/5-platform/packages/PackageService.js',
    './lark/5-platform/packages/PermissionManager.js',
    './lark/5-platform/packages/PermissionService.js',
    './lark/5-platform/packages/RepositoryManager.js',
    './lark/5-platform/packages/RepositoryService.js',
    './lark/5-platform/packages/RuntimeLoaderManager.js',
    './lark/5-platform/packages/RuntimeLoaderService.js',
    './lark/5-platform/packages/TrustManager.js',
    './lark/5-platform/packages/TrustService.js',
    './lark/5-platform/packages/loaders/BuiltinRuntimeLoader.js',
    './lark/5-platform/packages/loaders/LrfsRuntimeLoader.js',
    './lark/5-platform/packages/repositories/official.json',
    './lark/5-platform/packages/repositories/packages/dev.clipboardinspector.ldepkg',
    './lark/5-platform/packages/repositories/packages/dev.notificationinspector.ldepkg',
    './lark/5-platform/packages/repositories/packages/example.intenttester.ldepkg',
    './lark/5-platform/packages/repositories/packages/example.notes.ldepkg',
    './lark/5-platform/packages/repositories/sources/BuiltinRepositorySource.js',
    './lark/5-platform/process/ProcessManager.js',
    './lark/5-platform/process/ProcessService.js',
    './lark/5-platform/recovery/RecoveryManager.js',
    './lark/5-platform/recovery/RecoveryService.js',
    './lark/5-platform/recovery/RestoreManager.js',
    './lark/5-platform/recovery/RestoreService.js',
    './lark/5-platform/registry/ScopedServiceRegistry.js',
    './lark/5-platform/search/CommandPalette.js',
    './lark/5-platform/search/SearchService.js',
    './lark/5-platform/search/providers/ApplicationSearchProvider.js',
    './lark/5-platform/search/providers/CommandSearchProvider.js',
    './lark/5-platform/search/providers/FileSearchProvider.js',
    './lark/5-platform/search/providers/IntentSearchProvider.js',
    './lark/5-platform/search/providers/PackageSearchProvider.js',
    './lark/5-platform/search/providers/SessionSearchProvider.js',
    './lark/5-platform/security/SecurityManager.js',
    './lark/5-platform/security/SecurityService.js',
    './lark/5-platform/session/PowerService.js',
    './lark/5-platform/session/SessionManager.js',
    './lark/5-platform/session/SessionService.js',
    './lark/5-platform/session/UserEnvironmentOrchestrator.js',
    './lark/5-platform/settings/SettingsComponents.js',
    './lark/5-platform/settings/SettingsManager.js',
    './lark/5-platform/settings/SettingsService.js',
    './lark/5-platform/shortcuts/ShortcutManager.js',
    './lark/5-platform/shortcuts/ShortcutService.js',
    './lark/5-platform/storage/StorageDiscoveryService.js',
    './lark/5-platform/storage/VirtualDiskService.js',
    './lark/5-platform/theming/ThemeRepositoryManager.js',
    './lark/5-platform/theming/ThemeService.js',
    './lark/5-platform/theming/themes/BuiltinThemeSource.js',
    './lark/5-platform/users/UserManager.js',
    './lark/5-platform/users/UserProfileManager.js',
    './lark/5-platform/users/UserProfileService.js',
    './lark/5-platform/users/UserService.js',
    './lark/5-platform/users/UserSettingsManager.js',
    './lark/5-platform/users/UserSettingsService.js',
    './lark/5-platform/widgets/CalendarWidget.js',
    './lark/5-platform/widgets/ClockWidget.js',
    './lark/5-platform/widgets/NotesWidget.js',
    './lark/5-platform/widgets/WeatherWidget.js',
    './lark/5-platform/widgets/WidgetManager.js',
    './lark/5-platform/widgets/WidgetRegistry.js',
    './lark/5-platform/widgets/WidgetService.js',
    './lark/5-platform/window/WindowFrame.js',
    './lark/5-platform/window/WindowManager.js',
    './lark/5-platform/window/WindowService.js',
    './lark/5-platform/window/dialogs/OpenWithDialog.js',
    './lark/5-platform/window/dialogs/PropertiesDialog.js',
    './lark/5-platform/workspace/WorkspaceManager.js',
    './lark/5-platform/workspace/WorkspaceService.js',
    './lark/6-apps/system/EventViewer.js',
    './lark/6-apps/system/FileManager.js',
    './lark/6-apps/system/Guardian.js',
    './lark/6-apps/system/Notepad.js',
    './lark/6-apps/system/Settings.js',
    './lark/6-apps/system/SoftwareCenter.js',
    './lark/6-apps/system/TaskManager.js',
    './lark/6-apps/system/Terminal.js',
    './lark/7-sdk/builders/ManifestBuilder.js',
    './lark/7-sdk/index.js',
    './lark/7-sdk/registry/ApiRegistry.js',
    './lark/7-sdk/templates/background/App.js',
    './lark/7-sdk/templates/background/README.md',
    './lark/7-sdk/templates/background/manifest.json',
    './lark/7-sdk/templates/dialog/App.js',
    './lark/7-sdk/templates/dialog/README.md',
    './lark/7-sdk/templates/dialog/manifest.json',
    './lark/7-sdk/templates/minimal/App.js',
    './lark/7-sdk/templates/minimal/README.md',
    './lark/7-sdk/templates/minimal/manifest.json',
    './lark/7-sdk/templates/search-provider/README.md',
    './lark/7-sdk/templates/search-provider/SearchProvider.js',
    './lark/7-sdk/templates/search-provider/manifest.json',
    './lark/7-sdk/templates/widget/README.md',
    './lark/7-sdk/templates/widget/Widget.js',
    './lark/7-sdk/templates/widget/manifest.json',
    './lark/8-developer/DeveloperOptionsService.js',
    './lark/8-developer/PlatformArchitectureValidation.js',
    './lark/8-developer/diagnostics/Diagnostics.js',
    './lark/8-developer/quality/ArchitectureLinter.js',
    './lark/8-developer/quality/HealthReporter.js',
    './lark/8-developer/quality/PLACEHOLDER.md',
    './lark/8-developer/quality/SdkCompatibilityChecker.js',
    './lark/8-developer/quality/test-health.js',
    './lark/8-developer/testing/PLACEHOLDER.md',
    './lark/8-developer/testing/TestHelpers.js',
    './lark/8-developer/testing/mock-projects.js',
    './lark/9-ui/NEXT_design.css',
    './lark/9-ui/NEXT_omni.css',
    './lark/9-ui/NEXT_shell.css',
    './lark/9-ui/components/WorkspaceTabs.js',
    './lark/9-ui/omni.css',
    './lark/9-ui/sfi.ttf',
    './lark/9-ui/theme.css',
    './package.json'
];

// 1. Install Event: Triggered when the browser sees this version of the Service Worker for the first time.
// We use this phase to fetch all the files in ASSETS_TO_CACHE and save them to the browser's local cache.
self.addEventListener('install', event => {
    console.log(`[Service Worker] Installing new cache version: ${CACHE_NAME}`);
    event.waitUntil(
        caches.open(CACHE_NAME).then(cache => {
            return Promise.all(
                [...new Set(ASSETS_TO_CACHE)].map(url => {
                    // We append ?cb=Date.now() to bypass the browser's HTTP cache 
                    // and ensure we download the truly latest version from the server.
                    return fetch(url + '?cb=' + Date.now(), { cache: 'no-store' }).then(response => {
                        if (!response.ok) throw new Error('Fetch failed for ' + url);
                        return cache.put(url, response);
                    });
                })
            );
        }).then(() => {
            console.log('[Service Worker] Install complete. Skipping wait...');
            // Force the waiting service worker to become the active service worker.
            self.skipWaiting();
        })
    );
});

// 2. Activate Event: Triggered when this Service Worker officially takes control.
// We use this phase to clean up any old, outdated caches so we don't waste disk space.
self.addEventListener('activate', event => {
    console.log('[Service Worker] Activating...');
    event.waitUntil(
        caches.keys().then(keys => {
            return Promise.all(
                keys.map(key => {
                    // If we find a cache that doesn't match our current CACHE_NAME, delete it.
                    if (key !== CACHE_NAME) {
                        console.log(`[Service Worker] CACHE UPDATED! Deleting old cache: ${key}`);
                        return caches.delete(key);
                    }
                })
            );
        }).then(() => {
            console.log(`[Service Worker] NOW USING CACHE: ${CACHE_NAME}`);
            // Take control of all open pages immediately
            return self.clients.claim();
        })
    );
});

// 3. Message Event: Allows the webpage (ServiceWorkerManager) to send commands to the worker.
self.addEventListener('message', event => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('[Service Worker] Received SKIP_WAITING message');
        self.skipWaiting();
    }
});

// 4. Fetch Event: Intercepts every single network request made by the OS.
// We try to serve the file from our local cache first. If it's missing, we fetch it from the network.
self.addEventListener('fetch', event => {
    event.respondWith(
        caches.match(event.request, { ignoreSearch: true })
            .then(response => response || fetch(event.request))
            .catch(err => {
                // If the user is entirely offline and requests a file we don't have, fallback to index.html
                console.warn('[Service Worker] Network fetch failed, serving fallback:', err);
                return caches.match('./index.html', { ignoreSearch: true });
            })
    );
});
