import { ShellComponent } from '../../desktop/shell/ShellComponent.js';

/**
 * PlatformEnvironmentSurface
 *
 * Responsibility:
 * Programmatically generates a DOM hierarchy that is structurally equivalent to the canonical
 * hierarchy defined in indexer.html (lines 89-108: .platform-environment > div > div > .platform-content-viewport).
 * Consumes platform.css stylesheet natively without inline styles.
 *
 * Visual Specification Invariant:
 * indexer.html serves as the canonical visual contract for platform environment layout.
 * Programmatic DOM generated by this surface MUST remain structurally equivalent.
 *
 * Does NOT:
 * - Contain setup-specific, installer-specific, or recovery-specific rendering logic
 * - Hardcode page forms or workflow steps (strictly environment-agnostic)
 */
export class PlatformEnvironmentSurface extends ShellComponent {
    constructor() {
        super();
        this.activeEnvironment = null;
        this.stepContainerElement = null;
        this.unsubscribeEnvChange = null;
    }

    /**
     * Bind active environment to this surface.
     * @param {Object} environment 
     */
    setActiveEnvironment(environment) {
        this.activeEnvironment = environment;
        if (this.stepContainerElement) {
            this.renderActiveStep();
        }
    }

    /**
     * Construct DOM hierarchy matching indexer.html contract.
     */
    render() {
        const root = document.createElement('div');
        root.className = 'platform-environment';

        const outerFrame = document.createElement('div');
        const innerFrame = document.createElement('div');
        const contentViewport = document.createElement('div');
        contentViewport.className = 'platform-content-viewport';

        innerFrame.appendChild(contentViewport);
        outerFrame.appendChild(innerFrame);
        root.appendChild(outerFrame);

        this.element = root;
        this.stepContainerElement = contentViewport;

        // Render current step if environment is already attached
        if (this.activeEnvironment) {
            this.renderActiveStep();
        }

        return root;
    }

    /**
     * Renders active workflow step into stepContainerElement.
     */
    renderActiveStep() {
        if (!this.stepContainerElement || !this.activeEnvironment) return;

        this.stepContainerElement.innerHTML = '';
        const activeStep = typeof this.activeEnvironment.getCurrentStep === 'function' 
            ? this.activeEnvironment.getCurrentStep() 
            : null;

        if (activeStep && typeof activeStep.render === 'function') {
            const stepNode = activeStep.render(this.activeEnvironment.getContext(), this.activeEnvironment);
            if (stepNode instanceof Node) {
                this.stepContainerElement.appendChild(stepNode);
            } else if (typeof stepNode === 'string') {
                this.stepContainerElement.innerHTML = stepNode;
            }

            if (typeof activeStep.bind === 'function') {
                activeStep.bind(this.stepContainerElement, this.activeEnvironment.getContext(), this.activeEnvironment);
            }
        }
    }

    resume() {
        super.resume();
        if (this.activeEnvironment) {
            this.renderActiveStep();
        }
    }
}
